// Code generated by "go run ./cmd/reset"; DO NOT EDIT.

package models

func (m *Metrics) Reset() {
	if m == nil {
		return
	}

	m.ID = ""
	m.MType = ""
	if m.Delta != nil {
		*m.Delta = 0
	}
	if m.Value != nil {
		*m.Value = 0
	}
}
